### ISSUE TITLE
Configure ingress class

### ISSUE THREAD

**Issue by spynode** [lyft/flinkk8soperator#131]
Many clusters have several ingress classes deployed and it would be quite useful to have ability to specify ingress class in flinkk8soperator config.

**Comment by Smana** [comment]
Generally speaking that would be useful to update the ingress annotations. In our case we make use of many nginx ingress configuration items such as:
```
 apiVersion: extensions/v1beta1                                                                                                                                                                                    
 kind: Ingress                                                                                                                                                                                                     
 metadata:                                                                                                                                                                                                         
   annotations:                                                                                                                                                                                                    
     external-dns.alpha.kubernetes.io/hostname: myapp.domain.tld                                                                                                                              
     external-dns.alpha.kubernetes.io/target: loadbalancer-vip.domain.tld                                                                                                                             
     external-dns.alpha.kubernetes.io/ttl: "120"                                                                                                                                                                   
     kubernetes.io/ingress.class: nginx                                                                                                                                                                            
     nginx.ingress.kubernetes.io/auth-signin: https://proxy-url/oauth2/start?rd=https://myapp.domain.tld/                                                                        
     nginx.ingress.kubernetes.io/auth-url: https://proxy-url/oauth2/auth                                                                                                                              
     nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,192.168.0.0/16,172.16.0.0/12 
```
