### ISSUE TITLE
Configuring Prometheus metric reporter

### ISSUE THREAD

**Issue by aleksandr-spb** [lyft/flinkk8soperator#137]
Good day.
We use Flink Prometheus metric reporter (https://ci.apache.org/projects/flink/flink-docs-release-1.9/monitoring/metrics.html#prometheus-orgapacheflinkmetricsprometheusprometheusreporter) in conjunction  with Prometheus Operator ServiceMonitor (https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#related-resources) to collect Flink cluster metrics.  But when we tried to swithc to flinkk8soperator we encountered some difficulties. 
To collect metrics we need to expose metric reporter port 9249 on both services- JobManager and TaskManager, but FlinkApplication configuration does not allow configuring container ports, and flinkk8soperator creates a Service only for JobManager.
Can we configure FlinkApplication to collect metrics without changing the source code of flinkk8soperator?

**Comment by anandswaminathan** [comment]
@aleksandr-spb Can you share more information on the difficulties? 

Is `metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter` not working?  Correct me if my understanding is incorrect. Based on doc- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/: the `ports` is primarily informational. Not specifying a port here does not prevent that port from being exposed

**Comment by aleksandr-spb** [comment]
1. PrometheusReporter is working. But we cant access it through Prometheus Operator ServiceMonitor. ServiceMonitor needs metric endpoints that are provided by the Services. We need to explicitly configure port 9249 on the corresponding Service (JobmanagerService and TaskManagerService).
2. FlinkK8SOperator only creates a Service for Jobmanager, but we need to get metrics from TaskManager also through the Service.
I create branch in fork - https://github.com/aleksandr-spb/flinkk8soperator/tree/supportingServiceMonitor. It works, but I'm not sure if my decision is correct

**Comment by anandswaminathan** [comment]
@aleksandr-spb @srleyva 

For (1) I think we can think of adding "additionalServicePorts" either in CRD, or operator config that can be propagated to the service.

For (2) Just to understand more - essentially we need to create a separate TaskManager service - this service need not be versioned like Jobmanager service - and can live for the lifetime of the application. Also we can throw this behind a config flag.  

Is that correct ?

**Comment by aleksandr-spb** [comment]
That is correct.

**Comment by iravid** [comment]
Posted this on the Slack channel, but for anyone interested, here's a PodMonitor spec that can monitor applications deployed by the operator. This can serve as a workaround until changes are made in the services that the operator deploys:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flink-podmonitor
  namespace: <application namespace>
spec:
  namespaceSelector:
    matchNames:
    - <application namespace>
  selector:
    matchLabels:
      <application labels>
  podMetricsEndpoints:
    - path: /
      interval: 30s
      relabelings:
      # The Kubernetes service discovery will create a target for every port on the
      # Flink containers. So first, keep only the targets for the RPC port.
      - sourceLabels:
        - __meta_kubernetes_pod_container_port_number
        action: keep
        regex: "6123"
      # Next, we don't actually want the RPC port. So replace the port number for
      # the container port label and the endpoint label to 9249.
      - targetLabel: __meta_kubernetes_pod_container_port_number
        replacement: "9249"
      - targetLabel: endpoint
        replacement: "9249"
      # Finally, override the special __address__ label that specifies what IP:Port
      # Prometheus should scrape with the right value.
      - sourceLabels:
        - __meta_kubernetes_pod_ip
        - __meta_kubernetes_pod_container_port_number
        separator: ":"
        targetLabel: __address__
```
