### ISSUE TITLE
jobmanager.rpc.address doesn't get injected into application

### ISSUE THREAD

**Issue by YuvalItzchakov** [lyft/flinkk8soperator#19]
While attempting to run a Flink job on an AWS EKS cluster using the operator, the task managers start up, but fail immediatly due to `jobmanager.rpc.address` not being set:

```
2019-06-05 13:10:48,097 ERROR org.apache.flink.runtime.taskexecutor.TaskManagerRunner       - TaskManager initialization failed.
org.apache.flink.util.ConfigurationException: Config parameter 'Key: 'jobmanager.rpc.address' , default: null (fallback keys: [])' is missing (hostname/address of JobManager to connect to).
	at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.getJobManagerAddress(HighAvailabilityServicesUtils.java:151)
	at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.createHighAvailabilityServices(HighAvailabilityServicesUtils.java:87)
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.<init>(TaskManagerRunner.java:129)
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.runTaskManager(TaskManagerRunner.java:332)
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner$1.call(TaskManagerRunner.java:302)
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner$1.call(TaskManagerRunner.java:299)
	at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
	at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.main(TaskManagerRunner.java:299)
```

When describing the pod for both the jobmanager and taskmanager, I can see the `jobmanager.rpc.address` set under `OPERATOR_FLINK_CONFIG`: 

```
OPERATOR_FLINK_CONFIG: blob.server.port: 6125

high-availability.cluster-id: foo-59fd197e
jobmanager.rpc.address: foo-59fd197e
jobmanager.heap.size: 512
jobmanager.rpc.port: 6123
jobmanager.web.port: 8081
metrics.internal.query-service.port: 50101
query.server.port: 6124
taskmanager.numberOfTaskSlots: 2
```

Everything is running under the `flink-operator` namespace.

When the taskmanager loads, it emits the following:

```
Starting Task Manager
config file:
jobmanager.rpc.address:
jobmanager.rpc.port: 6123
jobmanager.heap.size: 1024m
taskmanager.heap.size:
taskmanager.numberOfTaskSlots:
parallelism.default: 1
metrics.internal.query-service.port:
taskmanager.host :
blob.server.port: 6124
query.server.port: 6125
used deprecated key `taskmanager.heap.mb`, please replace with key `taskmanager.heap.size`
```

Operator description:

```
apiVersion: flink.k8s.io/v1alpha1
kind: FlinkApplication
metadata:
  name: foo
  namespace: flink-operator
  annotations:
  labels:
    environment: production
spec:
  image: {{ printf "%s:%s" .Values.image.name .Values.image.tag }}
  flinkConfig:
    taskmanager.heap.size: 200
    state.backend.fs.checkpointdir: {{ .Values.job.checkpointDir }}
    state.checkpoints.dir: {{ .Values.job.checkpointDir }}
    state.savepoints.dir: {{ .Values.job.savepointDir }}
  jobManagerConfig:
    envConfig:
      env:
      - name: BAR
        value: "0"
      - name: BAZ
        value: "1"
    resources:
      requests:
        memory: "1Gi"
        cpu: "2"
    replicas: 1
  taskManagerConfig:
    envConfig:
      env:
        - name: BAR
          value: "0"
        - name: BAZ
          value: "1"
    taskSlots: 2
    resources:
      requests:
        memory: "4Gi"
        cpu: "1"
  flinkVersion: "1.8"
  jarName: "foo.jar"
  parallelism: 4
  entryClass: {{ .Values.job.entryPoint }}
  programArgs: {{ .Values.job.args }}

```

If I bash into the jobmanager pod and `printenv`, I definitely see the values being 
set in the `OPERATOR_FLINK_CONFIG`

```
OPERATOR_FLINK_CONFIG=blob.server.port: 6125
jobmanager.heap.size: 512
jobmanager.rpc.port: 6123
jobmanager.web.port: 8081
metrics.internal.query-service.port: 50101
query.server.port: 6124
taskmanager.heap.size: 2048
taskmanager.numberOfTaskSlots: 2

high-availability.cluster-id: foo-59fd197e
jobmanager.rpc.address: foo-59fd197e
```

But they don't get injected into `flink-conf.yaml`:

```
#==============================================================================
# Common
#==============================================================================

# The external address of the host on which the JobManager runs and can be
# reached by the TaskManagers and any clients which want to connect. This setting
# is only used in Standalone mode and may be overwritten on the JobManager side
# by specifying the --host <hostname> parameter of the bin/jobmanager.sh executable.
# In high availability mode, if you use the bin/start-cluster.sh script and setup
# the conf/masters file, this will be taken care of automatically. Yarn/Mesos
# automatically configure the host name based on the hostname of the node where the
# JobManager runs.

jobmanager.rpc.address:

# The RPC port where the JobManager is reachable.

jobmanager.rpc.port: 6123
```
