### ISSUE TITLE
Question: why is flink-conf.yaml needed for building job image?

### ISSUE THREAD

**Issue by functicons** [lyft/flinkk8soperator#77]
I found there are 2 ways I can specify Flink config,

1) one is the `flinkConfig` property of the [custom resource](https://github.com/lyft/flinkk8soperator/blob/master/docs/crd.md), for example:

```
spec:
  image: docker.io/lyft/wordcount-operator-example:{sha}
  flinkConfig:
    taskmanager.heap.size: 200
    state.backend.fs.checkpointdir: file:///checkpoints/flink/checkpoints
    state.checkpoints.dir: file:///checkpoints/flink/externalized-checkpoints
    state.savepoints.dir: file:///checkpoints/flink/savepoints
```
2) [flink-conf.yaml](https://github.com/lyft/flinkk8soperator/blob/master/examples/wordcount/flink-conf.yaml) which is copied into the job Docker image.

So, my question is why there are 2 ways of specifying Flink config? In particular, why is the 2nd needed?
