### ISSUE TITLE
Fractional {job,task}manager.heap.size crashes Flink

### ISSUE THREAD

**Issue by JonnyIncognito** [lyft/flinkk8soperator#97]
The offHeapMemoryFraction can cause fractional values to be written to flink-conf.yaml, which crashes Flink on startup:

```
/opt/flink/bin/config.sh: line 261: [ERROR] >> 20: syntax error: operand expected (error token is "[ERROR] >> 20")
[ERROR] Configured JobManager memory size is not a valid value. Please set 'jobmanager.heap.size' in flink-conf.yaml.
```

For example, the following FlinkApplication...

```
  jobManagerConfig:
    resources:
      requests:
        memory: "4Gi"
        cpu: "1.0"
    offHeapMemoryFraction: 0.15
    replicas: 1
  taskManagerConfig:
    taskSlots: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "1.0"
    offHeapMemoryFraction: 0.3
```

... causes the following to be generated:

```
jobmanager.heap.size: 3481.6
taskmanager.heap.size: 2867.2
```

Above is using v0.2.0
